# ----------------------------------------------------------------------------
# Amiga-os3-specific options
# ----------------------------------------------------------------------------

override HOST = windows
override SUBTARGET = 
override TARGET = amigaos3

RTG := YES
AGA := 685

PPC := NO
override  NETSURF_FB_FONTLIB := freetype
#override  NETSURF_FB_FONTLIB := internal
override  NETSURF_USE_MOZJS := NO
NETSURF_FS_BACKING_STORE := YES

ifeq ($(PPC),YES)
GCCVER := 2
CC_MINOR := 2
CC := ppc-amigaos-gcc -g
CFLAGS += -IADE:include -ITyp:usr/local/amiga/m68k-amigaos/sys-include -LTyp:usr/local/amiga/m68k-amigaos/lib -Ityp:opt/share/include
else
CC := m68k-amigaos-gcc -s -O3 -fomit-frame-pointer -m68060 -mnobitfield -ffast-math -fexpensive-optimizations
# Optimisation levels
#CC := m68k-amigaos-gcc -g
endif

ifeq ($(RTG),YES)
CFLAGS += -DRTG
else ifeq ($(AGA),685) 
CFLAGS += -DAGA685
else ifeq ($(AGA),676)
CFLAGS += -DAGA676
endif

ifeq ($(NETSURF_FB_FONTLIB),internal)
CFLAGS += -DNOTTF
endif

ifeq ($(NETSURF_USE_MOZJS),YES)
CFLAGS += -DJS
endif

#override NETSURF_UA_FORMAT_STRING := "Greyhound/%d.%d (%s,%s)"

# Force using glibc internal iconv implementation instead of external libiconv
# Valid options: YES, NO
NETSURF_USE_LIBICONV_PLUG := NO

# Enable Greyhound's use of librosprite for displaying RISC OS Sprites
# Valid options: YES, NO, AUTO
NETSURF_USE_ROSPRITE := NO

# Enable Greyhound's use of libwebp for displaying WebPs
# Valid options: YES, NO
NETSURF_USE_WEBP := NO

# Enable Greyhound's use of libsvgtiny for displaying SVGs
# Valid options: YES, NO
NETSURF_USE_NSSVG := NO

override  NETSURF_FB_FRONTEND := sdl
override  NETSURF_FB_RESPATH_sdl := /PROGDIR:Resources/
override  NETSURF_STRIP_BINARY := NO
override  NETSURF_USE_VIDEO := NO
override  NETSURF_FB_FONTPATH := /PROGDIR:Fonts/

# define additional CFLAGS and LDFLAGS requirements for pkg-configed libs here
NETSURF_FEATURE_HUBBUB_CFLAGS := -DWITH_HUBBUB
NETSURF_FEATURE_BMP_CFLAGS := -DWITH_BMP
NETSURF_FEATURE_GIF_CFLAGS := -DWITH_GIF
NETSURF_FEATURE_JS_CFLAGS := -DWITH_JS -DJS_HAS_FILE_OBJECT=0
NETSURF_FEATURE_MOZJS_CFLAGS := -DWITH_MOZJS -DJS_HAS_FILE_OBJECT=0