# ----------------------------------------------------------------------------
# Amiga-os3-specific options
# ----------------------------------------------------------------------------

override HOST = windows
override SUBTARGET =
override TARGET = amigaos3

RTG := YES
AGA := 685

PPC := NO
#override  GREYHOUND_FB_FONTLIB := freetype
override  GREYHOUND_FB_FONTLIB := internal
override  GREYHOUND_USE_MOZJS := NO
GREYHOUND_FS_BACKING_STORE := YES

ifeq ($(PPC),YES)
GCCVER := 2
CC_MINOR := 2
CC := ppc-amigaos-gcc -g
CFLAGS += -IADE:include -ITyp:usr/local/amiga/m68k-amigaos/sys-include -LTyp:usr/local/amiga/m68k-amigaos/lib -Ityp:opt/share/include
else
# Setze den Pfad zu den Header-Dateien
CFLAGS += -I$(CURDIR)/opt/greyhound/share/include
CFLAGS += -I$(CURDIR)/opt/libparserutils/src/utils
CFLAGS += -I$(CURDIR)/image
CFLAGS += -I$(CURDIR)/utils
# CFLAGS += -I/usr/include
# CFLAGS += -I/usr/include/libpng16

# Bibliotheken
LDFLAGS += -L$(CURDIR)/opt/greyhound/share/lib -lnsfb
# LDFLAGS += -lpng

# SDL für m68k-Amiga
CFLAGS += -I/opt/m68k-amigaos/include -I/opt/m68k-amigaos/include/SDL -I/opt/m68k-amigaos/usr/include/SDL
LDFLAGS += -L/opt/m68k-amigaos/lib -lSDL -lSDLmain

CC := m68k-amigaos-gcc -s -O3 -fomit-frame-pointer -m68060 -mnobitfield -ffast-math -fexpensive-optimizations
# Optimisation levels
#CC := m68k-amigaos-gcc -g
endif

ifeq ($(RTG),YES)
CFLAGS += -DRTG
else ifeq ($(AGA),685)
CFLAGS += -DAGA685
else ifeq ($(AGA),676)
CFLAGS += -DAGA676
endif

ifeq ($(GREYHOUND_FB_FONTLIB),internal)
CFLAGS += -DNOTTF
endif

ifeq ($(GREYHOUND_USE_MOZJS),YES)
CFLAGS += -DJS
endif

#override GREYHOUND_UA_FORMAT_STRING := "Greyhound/%d.%d (%s,%s)"

# Force using glibc internal iconv implementation instead of external libiconv
# Valid options: YES, NO
GREYHOUND_USE_LIBICONV_PLUG := NO

# Disable PNG because all PNG's will be converted to jpeg anyway by Greyhound Proxy
GREYHOUND_USE_PNG := NO

# Enable Greyhound's use of librosprite for displaying RISC OS Sprites
# Valid options: YES, NO, AUTO
GREYHOUND_USE_ROSPRITE := NO

# Enable Greyhound's use of libwebp for displaying WebPs
# Valid options: YES, NO
GREYHOUND_USE_WEBP := NO

# Enable Greyhound's use of libsvgtiny for displaying SVGs
# Valid options: YES, NO
GREYHOUND_USE_NSSVG := NO

override GREYHOUND_FB_FRONTEND := sdl
override GREYHOUND_FB_RESPATH_sdl := /PROGDIR:Resources/
override GREYHOUND_STRIP_BINARY := NO
override GREYHOUND_USE_VIDEO := NO
override GREYHOUND_FB_FONTPATH := /PROGDIR:Fonts/

# define additional CFLAGS and LDFLAGS requirements for pkg-configed libs here
GREYHOUND_FEATURE_HUBBUB_CFLAGS := -DWITH_HUBBUB
GREYHOUND_FEATURE_BMP_CFLAGS := -DWITH_BMP
GREYHOUND_FEATURE_GIF_CFLAGS := -DWITH_GIF
GREYHOUND_FEATURE_JS_CFLAGS := -DWITH_JS -DJS_HAS_FILE_OBJECT=0
GREYHOUND_FEATURE_MOZJS_CFLAGS := -DWITH_MOZJS -DJS_HAS_FILE_OBJECT=0
