--- openssl-1.0.1j-clean/Makefile	2014-12-04 15:13:14.300876329 +0100
+++ openssl-1.0.1j-amiga/Makefile	2014-12-04 15:12:36.853346912 +0100
@@ -12,7 +12,7 @@
 SHLIB_MAJOR=1
 SHLIB_MINOR=0.0
 SHLIB_EXT=
-PLATFORM=sunos-gcc
+PLATFORM=m68k-amigaos-gcc
 OPTIONS=enable-shared enable-zlib enable-md2 enable-rc5 --cross-compile-prefix=m68k-amigaos- -noixemul -liberty -lsocket no-asm no-ec_nistp_64_gcc_128 no-engine no-gmp no-hw no-jpake no-krb5 no-rfc3779 no-sctp no-store no-threads no-unit-test no-zlib-dynamic static-engine
 CONFIGURE_ARGS=shared no-hw no-engine no-threads zlib no-asm no-krb5 enable-md2 enable-rc5 --cross-compile-prefix=m68k-amigaos- sunos-gcc -noixemul -liberty -lsocket
 SHLIB_TARGET=
@@ -61,7 +61,7 @@
 
 CROSS_COMPILE= m68k-amigaos-
 CC= $(CROSS_COMPILE)gcc
-CFLAG= -DZLIB -noixemul -O3 -mv8 -Dssize_t=int
+CFLAG= -DZLIB -noixemul -O3
 DEPFLAG= -DOPENSSL_NO_EC_NISTP_64_GCC_128 -DOPENSSL_NO_ENGINE -DOPENSSL_NO_GMP -DOPENSSL_NO_JPAKE -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_SCTP -DOPENSSL_NO_STORE -DOPENSSL_NO_UNIT_TEST
 PEX_LIBS= 
 EX_LIBS= -liberty -lsocket  -lz
