/* utils/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 Greyhound Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "5cf8ef3a4ee5fd663eb7267b6e172060"

/* Revision testament checksum:
 * MD5:5cf8ef3a4ee5fd663eb7267b6e172060
 */

/* Revision testament: */
#define USERNAME "Artur-pc"
#define GECOS "U-ARTUR\\Artur-pc"
#define WT_ROOT "/projects/greyhound/"
#define WT_HOSTNAME "Artur"
#define WT_COMPILEDATE "27.07.2014"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "56556a677e86f24462542f951043b2f8d7647c31"
#define WT_MODIFIED 139
#define WT_MODIFICATIONS {\
  { ""framebuffer/fetch \342\200\224 kopia.c"", "??" }, \
  { ".mplayer/", "??" }, \
  { ".rnd", "??" }, \
  { "Assigns", "??" }, \
  { "Assigns.info", "??" }, \
  { "C.info", "??" }, \
  { "C/", "??" }, \
  { "ChangeLog", "??" }, \
  { "ChangeLog.info", "??" }, \
  { "Cygwin Terminal.lnk", "??" }, \
  { "Fonts/", "??" }, \
  { "GEN_font_internal.c", "??" }, \
  { "GrantPerms.exe", "??" }, \
  { "Libs.info", "??" }, \
  { "Libs/", "??" }, \
  { "Makefile", " M" }, \
  { "Makefile.config.wos", "??" }, \
  { "Makefile.win", "??" }, \
  { "Greyhound-nottf", "??" }, \
  { "Greyhound-nottf.7z", "??" }, \
  { "Greyhound-nottf.info", "??" }, \
  { "Greyhound.7z", "??" }, \
  { "Greyhound.dev", "??" }, \
  { "Greyhound.info", "??" }, \
  { "Greyhound.layout", "??" }, \
  { "Greyhound.zip", "??" }, \
  { "GreyhoundAGA", "??" }, \
  { "GreyhoundAGA-nottf", "??" }, \
  { "GreyhoundAGA-nottf.info", "??" }, \
  { "GreyhoundAGA.info", "??" }, \
  { "GreyhoundAGALow.info", "??" }, \
  { "GreyhoundAGAlow", "??" }, \
  { "GreyhoundAGAlow-nottf", "??" }, \
  { "GreyhoundAGAlow-nottf.info", "??" }, \
  { "GreyhoundAGAwindow", "??" }, \
  { "GreyhoundAGAwindow.info", "??" }, \
  { "GreyhoundJS.info", "??" }, \
  { "Perms.txt", "??" }, \
  { "Resources.info", "??" }, \
  { "amiga/dist/Rexx/ShowTitles-1.nsrx", "??" }, \
  { "amiga/dist/Rexx/viewsource-1.nsrx", "??" }, \
  { "amiga/resources/AdBlock-1.css", "??" }, \
  { "amiga/resources/Pointers/Right-1.info", "??" }, \
  { "amiga/resources/Pointers/RightDown-1.info", "??" }, \
  { "amiga/resources/ca-bundle-1", "??" }, \
  { "amiga/utf8.h", " M" }, \
  { "amigaos3/", "??" }, \
  { "atari/doc/DejaVu-1.txt", "??" }, \
  { "atari/doc/bugs-1", "??" }, \
  { "atari/doc/changes-1.txt", "??" }, \
  { "atari/gemtk/redrawslots-1.h", "??" }, \
  { "atari/gemtk/utils-1.c", "??" }, \
  { "atari/gemtk/utils-1.h", "??" }, \
  { "atari/gemtk/vaproto-1.c", "??" }, \
  { "atari/gemtk/vaproto-1.h", "??" }, \
  { "c2p8_040_asm.o", "??" }, \
  { "c2p8_040_dbl_asm.o", "??" }, \
  { "cocoa/BrowserWindowController-1.m", "??" }, \
  { "cocoa/PSMTabBarControl/PSMRolloverButton-1.h", "??" }, \
  { "cocoa/PSMTabBarControl/PSMRolloverButton-1.m", "??" }, \
  { "cocoa/PSMTabBarControl/PSMTabBarController-1.h", "??" }, \
  { "cocoa/PSMTabBarControl/PSMTabBarController-1.m", "??" }, \
  { "cocoa/compile-xib-1.sh", "??" }, \
  { "cocoa/font-1.h", "??" }, \
  { "cocoa/font-1.m", "??" }, \
  { "content/fetchers/about.c", " M" }, \
  { "convert_font", "??" }, \
  { "convert_font-noixemul", "??" }, \
  { "convert_font.exe", "??" }, \
  { "desktop.ini", "??" }, \
  { "desktop/version.c", " M" }, \
  { "diff.txt", "??" }, \
  { "env.info", "??" }, \
  { "font-noixemul.c", "??" }, \
  { "font.c", "??" }, \
  { "framebuffer/GEN_font_internal.ORG.c", "??" }, \
  { "framebuffer/GEN_font_internal.c", " M" }, \
  { "framebuffer/Makefile.target--", "??" }, \
  { "framebuffer/fb_thumbnail.c", "??" }, \
  { "framebuffer/fbtk/fbtk_bitmap.c", "??" }, \
  { "framebuffer/fetch.c", " M" }, \
  { "framebuffer/font_internal.h", " M" }, \
  { "framebuffer/framebuffer.c", " M" }, \
  { "framebuffer/gui--.c", "??" }, \
  { "framebuffer/res/fonts/glyph_data", " M" }, \
  { "framebuffer/res/fonts/glyph_data_org", "??" }, \
  { "gtk/res/C/Messages-1", "??" }, \
  { "gtk/res/C/credits-1.html", "??" }, \
  { "gtk/res/C/licence-1.html", "??" }, \
  { "gtk/res/de/welcome-1.html", "??" }, \
  { "mui.info", "??" }, \
  { "mui/", "??" }, \
  { "n++WorkspaceNS", "??" }, \
  { "nsgenbind.exe", "??" }, \
  { "pngout123.png", "??" }, \
  { "render/render_search.c", "??" }, \
  { "resources/AdBlock.css", "??" }, \
  { "resources/AdBlock.css.info", "??" }, \
  { "resources/FatMessages.info", "??" }, \
  { "resources/Messages", "??" }, \
  { "resources/Messages.info", "??" }, \
  { "resources/Options", "??" }, \
  { "resources/Options.info", "??" }, \
  { "resources/bookmarks.htm", "??" }, \
  { "resources/bookmarks.htm.info", "??" }, \
  { "resources/ca-bundle", "??" }, \
  { "resources/ca-bundle.info", "??" }, \
  { "resources/cookies", "??" }, \
  { "resources/cookies.info", "??" }, \
  { "resources/credits.html", "??" }, \
  { "resources/credits.html.info", "??" }, \
  { "resources/default.css", "??" }, \
  { "resources/default.css.info", "??" }, \
  { "resources/icons.info", "??" }, \
  { "resources/icons/", "??" }, \
  { "resources/internal.css", "??" }, \
  { "resources/internal.css.info", "??" }, \
  { "resources/licence.html", "??" }, \
  { "resources/licence.html.info", "??" }, \
  { "resources/greyhound.png", "??" }, \
  { "resources/greyhound.png.info", "??" }, \
  { "resources/nsdefault.css", "??" }, \
  { "resources/nsdefault.css.info", "??" }, \
  { "resources/quirks.css", "??" }, \
  { "resources/quirks.css.info", "??" }, \
  { "resources/theme.info", "??" }, \
  { "resources/theme/", "??" }, \
  { "resources/welcome.html", "??" }, \
  { "resources/welcome.html.info", "??" }, \
  { "rexx/", "??" }, \
  { "utils/git-testament.pl", " M" }, \
  { "utils/nsoption.c", " M" }, \
  { "utils/nsoption.h", " M" }, \
  { "utils/testament-1.h", "??" }, \
  { "utils/testament.h", "??" }, \
  { "utils/testament_.h", "??" }, \
  { "utils/useragent.c", " M" }, \
  { "utils/utils_utils.c", "??" }, \
  { "website/", "??" } \
}

#endif
