/* build-windows-amigaos3/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 Greyhound Browser Project
 */

#ifndef GREYHOUND_REVISION_TESTAMENT
#define GREYHOUND_REVISION_TESTAMENT "0a99a5f595f73e01c4ff6e354f1427d0"

/* Revision testament checksum:
 * MD5:0a99a5f595f73e01c4ff6e354f1427d0
 */

/* Revision testament: */
#define USERNAME "root"
#define GECOS "root"
#define WT_ROOT "/src/"
#define WT_HOSTNAME "38c5d9904b87"
#define WT_COMPILEDATE "30.05.2025"
#define WT_BRANCHPATH "main"
#define WT_REVID "552933c8677c7b4d49af026880ef4b0ac73aa391"
#define WT_MODIFIED 1
#define WT_MODIFICATIONS {\
  { "build-windows-amigaos3/testament.h", " M" } \
}

#endif
