/* build-windows-amigaos3/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 Greyhound Browser Project
 */

#ifndef GREYHOUND_REVISION_TESTAMENT
#define GREYHOUND_REVISION_TESTAMENT "f9fb1e264c158260b90a6a7b70c3adac"

/* Revision testament checksum:
 * MD5:f9fb1e264c158260b90a6a7b70c3adac
 */

/* Revision testament: */
#define USERNAME "root"
#define GECOS "root"
#define WT_ROOT "/src/"
#define WT_HOSTNAME "38c5d9904b87"
#define WT_COMPILEDATE "28.05.2025"
#define WT_BRANCHPATH "main"
#define WT_REVID "c4cc2e8280ee102270713d7b8359fc6cdb9b4eac"
#define WT_MODIFIED 12
#define WT_MODIFICATIONS {\
  { "Makefile.config", " M" }, \
  { "build-windows-amigaos3/testament.h", " M" }, \
  { "build-windows-amigaos3/utils_messages.o", "??" }, \
  { "build-windows-amigaos3/utils_nsoption.o", "??" }, \
  { "build-windows-amigaos3/utils_nsurl.o", "??" }, \
  { "build-windows-amigaos3/utils_punycode.o", "??" }, \
  { "build-windows-amigaos3/utils_talloc.o", "??" }, \
  { "build-windows-amigaos3/utils_url.o", "??" }, \
  { "build-windows-amigaos3/utils_useragent.o", "??" }, \
  { "build-windows-amigaos3/utils_utf8.o", "??" }, \
  { "build-windows-amigaos3/utils_utf8proc.o", "??" }, \
  { "utils/utils.c", " M" } \
}

#endif
